# Generated by Django 4.2.16 on 2024-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Тег')),
                ('color', models.CharField(choices=[('GREEN', 'Зеленый'), ('RED', 'Красный'), ('ORANGE', 'Оранжевый'), ('BLUE', 'Синий'), ('GRAY', 'Серый')], max_length=16, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='card',
            name='part_of_speech',
            field=models.CharField(choices=[('verb', 'глагол'), ('interjection', 'междометие'), ('pronoun', 'местоимение'), ('adverb', 'наречие'), ('preposition', 'предлог'), ('adjective', 'прилагательное'), ('conjunction', 'союз'), ('noun', 'существительное')], default='noun', max_length=32, verbose_name='Часть речи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='tag',
            field=models.ManyToManyField(to='cards.tag', verbose_name='Тег'),
        ),
    ]
