# Generated by Django 4.2.16 on 2024-11-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_tag_card_part_of_speech_card_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('n_singular', 'Единственное число'), ('n_plural', 'Множественное число'), ('v_base_form', 'Инфинитив (базовая форма)'), ('v_past_simple', 'Прошедшее время'), ('v_past_participle', 'Причастие прошедшего времени'), ('v_present_participle', 'Причастие настоящего времени'), ('v_third_person_singular', '3 лицо, ед. число, наст. время'), ('a_regular', 'Основная форма'), ('a_comparative', 'Сравнительная степень'), ('a_superlative', 'Превосходная степень')], max_length=32, verbose_name='Тип')),
                ('form', models.CharField(max_length=256, verbose_name='Форма')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='cards.card', verbose_name='Слово')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=256, verbose_name='English')),
                ('rus', models.CharField(max_length=256, verbose_name='Russian')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='cards.card', verbose_name='Слово')),
            ],
        ),
    ]
