# Generated by Django 4.2.16 on 2024-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_form_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликована'),
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='translation_secondary',
            field=models.TextField(blank=True, null=True, verbose_name='Перевод дополнительный'),
        ),
        migrations.AlterField(
            model_name='card',
            name='word',
            field=models.CharField(max_length=128, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='form',
            name='type',
            field=models.CharField(choices=[('1_n_singular', 'Единственное число'), ('2_n_plural', 'Множественное число'), ('1_v_base_form', 'Инфинитив (базовая форма)'), ('2_v_past_simple', 'Прошедшее время'), ('3_v_past_participle', 'Причастие прошедшего времени'), ('4_v_present_participle', 'Причастие настоящего времени'), ('5_v_third_person_singular', '3 лицо, ед. число, наст. время'), ('1_a_regular', 'Основная форма'), ('2_a_comparative', 'Сравнительная степень'), ('3_a_superlative', 'Превосходная степень')], max_length=32, verbose_name='Тип'),
        ),
    ]
