# Generated by Django 4.2.16 on 2024-11-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_is_published_card_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='eng',
            field=models.TextField(max_length=256, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='example',
            name='rus',
            field=models.TextField(max_length=256, verbose_name='Russian'),
        ),
    ]
