# Generated by Django 4.2.16 on 2024-11-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapcauser',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
