# Generated by Django 4.2.16 on 2024-11-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tapcauser_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapcauser',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='Студент'),
        ),
    ]
