# Generated by Django 4.2.16 on 2024-11-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tapcauser_is_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_secret',
            field=models.CharField(max_length=64, verbose_name='Секрет'),
        ),
    ]
