# Generated by Django 4.1.13 on 2024-12-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_otp_options_alter_otp_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapcauser',
            name='theme_dark',
            field=models.BooleanField(default=False, verbose_name='Темная тема'),
        ),
        migrations.AlterField(
            model_name='tapcauser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
