# Generated by Django 4.1.13 on 2024-12-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tapcauser_theme_dark_alter_tapcauser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tapcauser',
            name='theme_dark',
        ),
    ]
