# Generated by Django 4.1.13 on 2024-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_form_options'),
        ('users', '0007_remove_tapcauser_theme_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapcauser',
            name='tags',
            field=models.ManyToManyField(to='cards.tag', verbose_name='Категории для изучения'),
        ),
    ]
